name: 'Dependabot JIRA Action'
description: 'Creates JIRA issues from dependabot alerts'
author: 'Sprout Tech LLC'
inputs:
  jiraIssueLabel:
    required: true
    description: 'JIRA issue labels'
    default: "dependabot"
  jiraProjectKey:
    required: true
    description: 'JIRA issue project key'
  jiraIssueType:
    required: true
    description: 'JIRA issue type'
    default: "Bug"
  githubRepo:
    required: true
    description: 'Repo to look for dependabot pulls'
    default: "repo-name"
  githubOwner:
    required: true
    description: 'Owner of the repo'
    default: "repo-name"
  closeIssueOnMerge:
    required: true
    description: 'Whether to auto-resolve jira issue when PR is merged into branch'
    default: "false"
  ikProjectDomain:
    required: false
    description: 'The live url of the project'
  jiraProjectPage:
    required: false
    description: 'The confluence document Url'
  ikDevSite:
    required: false
    description: 'The dev url'
  ikTeamworkProject:
    required: false
    description: 'The teamwork prject Url'
  frameworksInfo:
    required: false
    description: 'The teamwork prject Url'
  databaseInfo:
    required: false
    description: 'The teamwork prject Url'
  serverInfo:
    required: false
    description: 'The teamwork prject Url'
  additionalLinks:
    required: false
    description: 'The teamwork prject Url'
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: 'copy'
  color: 'purple'
